export const reciActions = {
    RECIPE_NAME: 'RECIPE_NAME',
    RECIPE_DESC: 'RECIPE_DESC',
    RECIPE_INST: 'RECIPE_INST',
    RECIPE_VALUE: 'RECIPE_VALUE',
    CREATE_RECIPE: 'CREATE_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',
    UPDATE_RECIPE: 'UPDATE_RECIPE',
    RECIPES: 'RECIPES',
    CURRENT_USER_RECIPES: 'CURRENT_USER_RECIPES'
}