export const authActions = {
    USERNAME: 'USERNAME',
    PASSWORD: 'PASSWORD',
    CONFIRM_PASSWORD: 'CONFIRM_PASSWORD',
    AUTHENTICATED_USER: 'AUTHENTICATED_USER',
    LOG_OUT_USER: 'LOG_OUT_USER',
    CREATE_USER: 'CREATE_USER',
    DELTE_USER: 'DELETE_USER',
    CHECK_LOGIN_STATE: 'CHECK_LOGIN_STATE',
}